[package]
name = "net-tracker"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
thiserror = "1"
chrono = { version = "0.4", features = [ "serde" ] }
